@startuml
class AppLayoutStudent {
    - VerticalLayout topNavbarPanel
    - HorizontalLayout topNavbar
    - Avatar userAvatar
    - Span userInfo
    - WeatherService weatherService
    - buildNavbar(WeatherService weatherService) void
}
@enduml