@startuml
class HomeAdminView {
    - CoreService coreService
    - HomeAdminService homeAdminService
    - ScheduleService scheduleService
    - Div calendarGrid
    + beforeEnter(BeforeEnterEvent event) void
    - showGlobalSchedule() void
    - createEventCard(String title, String time, String subTitle, String color, int col, int startRow, int rowSpan) Div
}
@enduml